name: Deploy Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 🐳 Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 🐳 Build Docker Image
        uses: ./.github/actions/build-docker
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          context: .
          file: ./apps/web/.docker/Dockerfile
          tags: pchmn/monorepo-template-web:${{ github.sha}}
          push: true
